version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      # Set other backend-specific environment variables, e.g., DATABASE_URL, here.
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_GRAPHQL_URI: http://localhost:4000/graphql
